services:
  api:
    build:
      context: .
    command: /app/scripts/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_SECRET_KEY: development-secret-key
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      POSTGRES_DB: fjord
      POSTGRES_USER: fjord
      POSTGRES_PASSWORD: fjord
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fjord
      POSTGRES_USER: fjord
      POSTGRES_PASSWORD: fjord
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
