# Generated by Django 4.2.24 on 2025-09-27 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
