# Generated by Django 4.2.24 on 2025-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0002_alter_tip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardpresentation',
            name='center_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazardpresentation',
            name='center_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hazardpresentation',
            name='radius_meters',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hazardpresentation',
            name='boundary',
            field=models.JSONField(blank=True, default=list, help_text='Collection of GPS coordinates describing the area.'),
        ),
    ]
