# Generated by Django 4.2.24 on 2025-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0003_hazardpresentation_center_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='boundary',
            field=models.JSONField(blank=True, default=list, help_text='Collection of GPS coordinates describing the area.'),
        ),
        migrations.AddField(
            model_name='location',
            name='google_maps_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
