# Generated by Django 4.2.24 on 2025-10-13 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0004_location_boundary_location_google_maps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
